version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./tiendaonline.sql:/docker-entrypoint-initdb.d/tiendaonline.sql
  
  laravel-api:
    build:
      context: ./api-laravel
      dockerfile: dockerfile 
    container_name: laravel-api-container
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./api-laravel:/var/www/html