FROM php:latest

WORKDIR /var/www/html

# Instalar dependencias de PHP necesarias
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    && docker-php-ext-install zip pdo pdo_mysql

# Copiar los archivos del proyecto Laravel al contenedor
COPY . /var/www/html

# Cambiar los permisos de los archivos del proyecto
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html/storage

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Instalar dependencias de PHP usando Composer
RUN composer install

# Exponer el puerto 80 para el servidor web
EXPOSE 80

# Comando por defecto para iniciar el servidor web
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=80"]
